# -*- coding: utf-8 -*-
"""13/06

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13jFGxPRt7avUlQbzyf-cCvJWerSJjMrr
"""
# Version Publica!
# Este comentario seria el unico cambio que se le habria realizado al codigo nuevamente
import csv
id=0
edad=0
nombre=""
especie=""
diagnostico=""
lista_paciente = []
lista_pacientes = []
def cargar_pacientes():
    try:
        with open('pacientes.csv', 'r', newline='') as archivo_csv:
            lector_csv = csv.reader(archivo_csv)
            next(lector_csv, None)
            for fila in lector_csv:
                id, nombre, edad, especie, diagnostico = fila
                lista_pacientes.append([int(id), nombre, int(edad), especie, diagnostico])
    except FileNotFoundError:
        with open('pacientes.csv', 'w', newline='') as archivo_csv:
            escritor_csv = csv.writer(archivo_csv)
            escritor_csv.writerow(["id", "nombre", "edad", "especie", "diagnostico"])
def guardar_pacientes():
    with open('pacientes.csv', 'w', newline='') as archivo_csv:
        escritor_csv = csv.writer(archivo_csv)
        escritor_csv.writerow(["id", "nombre", "edad", "especie", "diagnostico"])
        escritor_csv.writerows(lista_pacientes)
def crear_paciente(id, nombre, edad, especie, diagnostico):
    lista_paciente = [id, nombre, edad, especie, diagnostico]
    lista_pacientes.append(lista_paciente)
    print(f"Paciente {nombre} creado exitosamente.")
    guardar_pacientes()
def leer_pacientes():
    if not lista_pacientes:
        print("No hay pacientes registrados.")
    else:
        print("Lista de pacientes:")
        for lista_paciente in lista_pacientes:
            print(f"ID: {lista_paciente[0]}, Nombre: {lista_paciente[1]}, Edad: {lista_paciente[2]}, Especie: {lista_paciente[3]}, Diagnóstico: {lista_paciente[4]}")
def actualizar_paciente(id):
    for lista_paciente in lista_pacientes:
        if lista_paciente[0] == id:
            nombre = input("Ingrese el nuevo nombre del paciente (dejar en blanco para mantener actual):\n")
            edad = input("Ingrese la nueva edad del paciente (dejar en blanco para mantener actual):\n")
            while not edad.isnumeric():
                edad = input("Debes ingresar una edad numérica válida:\n")
            edad = int(edad)
            especie = input("Ingrese la nueva especie del paciente (dejar en blanco para mantener actual):\n")
            diagnostico = input("Ingrese el nuevo diagnóstico del paciente (dejar en blanco para mantener actual):\n")
            if nombre and nombre.strip() != "":
                lista_paciente[1] = nombre
            if edad and edad.strip() != "":
                lista_paciente[2] = edad
            if especie and especie.strip() != "":
                lista_paciente[3] = especie
            if diagnostico and diagnostico.strip() != "":
                lista_paciente[4] = diagnostico
            print(f"Paciente con ID {id} actualizado exitosamente.")
            guardar_pacientes()
            return
    print(f"Paciente con ID {id} no encontrado.")
def eliminar_paciente(id):
    for lista_paciente in lista_pacientes:
        if lista_paciente[0] == id:
            lista_pacientes.remove(lista_paciente)
            print(f"Paciente con ID {id} eliminado exitosamente.")
            guardar_pacientes()
            return
    print(f"Paciente con ID {id} no encontrado.")
def mostrar_menu():
    print("\n--- Menú C.R.U.D. de Pacientes Veterinarios ---\n1. Crear paciente\n2. Leer pacientes\n3. Actualizar paciente\n4. Eliminar paciente\n5. Salir")
cargar_pacientes()
while True:
    mostrar_menu()
    opcion = input("Seleccione una opción:\n")
    while not opcion.isnumeric():
        opcion = input("Debes seleccionar una opción numérica:\n")
    if int(opcion) == 1:
        id = input("Ingrese el ID del paciente:\n")
        while not id.isnumeric():
            id = input("Debes ingresar un ID numérico:\n")
        id = int(id)
        nombre = input("Ingrese el nombre del paciente:\n")
        edad = input("Ingrese la edad del paciente:\n")
        while not edad.isnumeric():
            edad = input("Debes ingresar una edad numérica:\n")
        edad = int(edad)
        especie = input("Ingrese la especie del paciente:\n")
        diagnostico = input("Ingrese el diagnóstico del paciente:\n")
        crear_paciente(id, nombre, edad, especie, diagnostico)
    elif int(opcion) == 2:
        leer_pacientes()
    elif int(opcion) == 3:
        id = input("Ingrese el ID del paciente a actualizar:\n")
        while not id.isnumeric():
            id = input("Ingrese un ID de manera numérica:\n")
        id = int(id)
        actualizar_paciente(id)
    elif int(opcion) == 4:
        id = input("Ingrese el ID del paciente a eliminar:\n")
        while not id.isnumeric():
            id = input("Ingrese un ID de manera numérica:\n")
        id = int(id)
        eliminar_paciente(id)
    elif int(opcion) == 5:
        print("Saliendo del programa.\n¡Hasta luego!")
        break
    else:
        print("Opción no válida. Por favor, intente de nuevo.")